name: Tiers JSON Schema Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'tiers.json'
      - 'tiers.schema.json'
      - 'specs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install jsonschema
        run: pip install jsonschema
      - name: Validate tiers.json
        run: |
          python - <<'PY'
          import json
          from jsonschema import validate, Draft2020Validator
          with open('tiers.schema.json','r',encoding='utf-8') as f:
              schema=json.load(f)
          with open('tiers.json','r',encoding='utf-8') as f:
              data=json.load(f)
          Draft2020Validator.check_schema(schema)
          validate(instance=data, schema=schema)
          print("tiers.json is valid against tiers.schema.json")
          PY
